name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH_CLI: 'ApiClient/ApiClient.csproj'
  PROJECT_PATH_WRA: 'DigikeyApiWrapper/DigikeyApiWrapper.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3.3.0

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH_WRA }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH_WRA }} --no-restore --configuration Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2.2.1

    - name: 'Pack project'
      run: |
        dotnet pack ${{ env.PROJECT_PATH_WRA }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -p:SymbolPackageFormat=snupkg --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
        dotnet pack ${{ env.PROJECT_PATH_CLI }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -p:SymbolPackageFormat=snupkg --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
